### ISSUE TITLE
no puerto rican flag listed

### ISSUE THREAD

**Issue by kod3000** [seanherron/Flag-Webicons#1]
not sure what other flag is missing but thats a pretty important one right there.. :)

**Comment by seanherron** [comment]
Hi @kod3000,

It's not included as Puerto Rico isn't a sovereign state.

Thanks!
Sean

**Comment by kod3000** [comment]
According to the United States, yes, you're right. However, in the eyes of the UN it's a completely different story. I understand you're source is wikimedia and being its a US based company the facts are allowed to be incomplete, as is this list. :)

**Comment by seanherron** [comment]
Do you have a link for documentation for an official UN statement regarding
Puerto Rico's status as an independent, sovereign nation? If you can
provide explicit documentation regarding that I would consider a pull
request, but all documentation that I could find indicates the issue is
still in debate.
